// Root ESLint config for the whole workspace. The boundary rules encode the
// architecture from docs/ARCHITECTURE.md so it is enforced, not just described.
import eslint from '@eslint/js';
import prettier from 'eslint-config-prettier';
import boundaries from 'eslint-plugin-boundaries';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      'backend/drizzle/**',
      'backend/storage/**',
      // Generated by the shadcn CLI; kept verbatim so it can be regenerated.
      'frontend/src/components/ui/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Boundary checks need real module resolution: .js specifiers that point at .ts files, and the @/ alias.
    settings: {
      'import/resolver': {
        typescript: {
          project: ['backend/tsconfig.json', 'frontend/tsconfig.json', 'shared/tsconfig.json'],
        },
      },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
    },
  },

  // ---------------------------------------------------------------- backend
  {
    files: ['backend/**/*.ts'],
    languageOptions: { globals: globals.node },
    plugins: { boundaries },
    settings: {
      'boundaries/ignore': ['backend/src/**/*.test.ts', 'backend/src/testing/**'],
      'boundaries/elements': [
        { type: 'domain', mode: 'full', pattern: 'backend/src/domain/**' },
        { type: 'config', mode: 'full', pattern: 'backend/src/config/**' },
        {
          // The few files allowed to know about everything: they assemble the app.
          type: 'composition',
          mode: 'full',
          pattern: [
            'backend/src/container.ts',
            'backend/src/app.ts',
            'backend/src/server.ts',
            'backend/src/http/router.ts',
            'backend/src/infrastructure/db/repositories.ts',
            'backend/src/infrastructure/db/seed.ts',
            'backend/src/infrastructure/db/seedDemo.ts',
            'backend/src/infrastructure/db/migrate.ts',
          ],
        },
        { type: 'http', mode: 'full', pattern: 'backend/src/http/**' },
        { type: 'infrastructure', mode: 'full', pattern: 'backend/src/infrastructure/**' },
        {
          type: 'module-adapters',
          mode: 'full',
          pattern: 'backend/src/modules/*/adapters/**',
          capture: ['module'],
        },
        {
          type: 'module-ports',
          mode: 'full',
          pattern: 'backend/src/modules/*/ports/**',
          capture: ['module'],
        },
        { type: 'module', mode: 'full', pattern: 'backend/src/modules/*/**', capture: ['module'] },
      ],
    },
    rules: {
      'boundaries/element-types': [
        'error',
        {
          default: 'disallow',
          rules: [
            { from: 'domain', allow: ['domain'] },
            { from: 'config', allow: ['config'] },
            { from: 'composition', allow: ['*'] },
            { from: 'http', allow: ['http', 'domain', 'config', 'infrastructure', 'module-ports'] },
            {
              from: 'infrastructure',
              allow: ['infrastructure', 'domain', 'config', 'module-ports'],
            },
            { from: 'module-ports', allow: ['module-ports', 'domain', 'infrastructure'] },
            // Adapters implement their own module's ports and may share persistence helpers with other adapters.
            {
              from: 'module-adapters',
              allow: ['module-adapters', 'module-ports', 'domain', 'config', 'infrastructure'],
            },
            // Services, routes, controllers, presenters: never an adapter, not even their own.
            {
              from: 'module',
              allow: ['module', 'module-ports', 'domain', 'config', 'http', 'infrastructure'],
            },
            { from: 'module', allow: ['composition'], importKind: 'type' },
          ],
        },
      ],
    },
  },

  // --------------------------------------------------------------- frontend
  {
    files: ['frontend/**/*.{ts,tsx}'],
    languageOptions: { globals: globals.browser },
    plugins: { boundaries, 'react-hooks': reactHooks, 'react-refresh': reactRefresh },
    settings: {
      'boundaries/ignore': ['frontend/src/**/*.test.{ts,tsx}', 'frontend/src/testing/**'],
      'boundaries/elements': [
        {
          type: 'entry',
          mode: 'full',
          pattern: ['frontend/src/main.tsx', 'frontend/vite.config.ts'],
        },
        { type: 'app', mode: 'full', pattern: 'frontend/src/app/**' },
        {
          type: 'shared',
          pattern: ['frontend/src/lib/**', 'frontend/src/components/**', 'frontend/src/hooks/**'],
        },
        // First match wins: the public surface, then pages, then the general feature pattern.
        {
          type: 'feature-api',
          mode: 'full',
          pattern: 'frontend/src/features/*/index.ts',
          capture: ['feature'],
        },
        {
          type: 'feature-page',
          mode: 'full',
          pattern: 'frontend/src/features/*/pages/**',
          capture: ['feature'],
        },
        {
          type: 'feature',
          mode: 'full',
          pattern: 'frontend/src/features/*/**',
          capture: ['feature'],
        },
      ],
    },
    rules: {
      ...reactHooks.configs['recommended-latest'].rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      'boundaries/element-types': [
        'error',
        {
          default: 'disallow',
          rules: [
            { from: 'entry', allow: ['app', 'shared'] },
            // The app composes features through their public surface; pages are imported directly for routing.
            { from: 'app', allow: ['app', 'shared', 'feature-api', 'feature-page'] },
            { from: 'shared', allow: ['shared'] },
            // Pages are where features meet, but only through the other feature's public surface.
            {
              from: 'feature-page',
              allow: [
                'shared',
                'feature-api',
                'feature-page',
                ['feature', { feature: '${from.feature}' }],
              ],
            },
            // A feature's public surface re-exports its own internals and nothing else.
            { from: 'feature-api', allow: ['shared', ['feature', { feature: '${from.feature}' }]] },
            // Internals never reach outside their own feature.
            { from: 'feature', allow: ['shared', ['feature', { feature: '${from.feature}' }]] },
          ],
        },
      ],
    },
  },

  // Wiring and provider files legitimately export more than components.
  {
    files: [
      'frontend/src/app/router.tsx',
      'frontend/src/app/providers.tsx',
      'frontend/src/hooks/useTheme.tsx',
      'frontend/src/hooks/useAuthDialog.tsx',
    ],
    rules: { 'react-refresh/only-export-components': 'off' },
  },

  // Scripts and config files may log and use process freely.
  {
    files: [
      '**/*.config.{js,ts}',
      'backend/src/server.ts',
      'backend/src/infrastructure/db/seed.ts',
      'backend/src/infrastructure/db/migrate.ts',
    ],
    rules: { 'no-console': 'off' },
  },
  prettier,
);
