import { timestamp, uuid } from 'drizzle-orm/pg-core';

/** UUID primary key generated by Postgres. */
export const id = () => uuid().primaryKey().defaultRandom();

/**
 * created_at and updated_at. Repositories set updated_at with the database's own now(),
 * never the Node clock, so ordering by activity stays correct when app and database
 * servers disagree about the time (as a Docker VM and its host often do).
 */
export const timestamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
};
