import { timestamp, uuid } from 'drizzle-orm/pg-core';

/** UUID primary key generated by Postgres. */
export const id = () => uuid().primaryKey().defaultRandom();

/** created_at and updated_at. updated_at is maintained by the repositories. */
export const timestamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
};
